apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: cv-platform
  labels:
    app: model-serving
spec:
  selector:
    app: model-serving
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
