apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-platform-config
  namespace: cv-platform
data:
  CLOUD_SQL_INSTANCE: "project-38c56a6f-24a9-45fb-aef:us-central1:cv-postgres"

  CORS_ALLOW_ORIGINS: "https://cv-platform-fbd07.web.app,https://cv-platform-fbd07.firebaseapp.com"
