apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-platform-config
  namespace: cv-platform
data:
  # Cloud SQL: obtener db_public_ip de: tofu output db_public_ip
  CLOUD_SQL_INSTANCE: "CHANGE_ME:us-central1:cv-postgres"   # project:region:instance
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC: "training-jobs"
  KAFKA_OUTPUT_TOPIC: "model-trained"
  KAFKA_EVALUATED_TOPIC: "model-evaluated"
  WORKER_POLL_SECONDS: "5"
  WORKER_MAX_CONCURRENCY: "2"
  MODEL_REGISTRY_URL: "http://model-registry:8000/api/v1/models"
  MODEL_CACHE_DIR: "/data/models"
  MODEL_REGISTRY_AUTO_ACTIVATE: "true"
  MODEL_SERVING_AUTO_RELOAD: "true"
  MODEL_SERVING_AUTO_WARM: "true"
  INFER_UPLOAD_DIR: "/data/uploads"
  VAST_SSH_KEY_SRC: "/root/.ssh/id_ed25519_src"
  VAST_AUTO_SSH_KEY: "0"
  VAST_AUTO_REGISTER_SSH_KEY: "1"
  VAST_KEEP_INSTANCE_ON_FAILURE: "1"
  VAST_BLOCKED_COUNTRIES: "CN,RU,IR,HR"
  VAST_SSH_PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDstixq74hYBC85ovHQ6NlhgQHXV/klo1CbwNxfaSs/4 davse@davse"
  VAST_SSH_USER: "root"
  TRAIN_IMAGE: "davse/taco-yolo-service:latest"
  TRAIN_MODEL_GCS_BASE_URI: "gs://unlu-genai-serranodavid-computer_vision_yolo/artifacts"
