apiVersion: v1
kind: ServiceAccount
metadata:
  name: cv-platform-sa
  namespace: cv-platform
  annotations:
    iam.gke.io/gcp-service-account: cv-cloudsql-proxy@project-38c56a6f-24a9-45fb-aef.iam.gserviceaccount.com
