apiVersion: v1
kind: ServiceAccount
metadata:
  name: cv-platform-sa
  namespace: cv-platform
  annotations:
    # Reemplazar PROJECT_ID con el valor de: tofu output cloudsql_proxy_sa_email
    # Ejemplo: cv-cloudsql-proxy@mi-proyecto.iam.gserviceaccount.com
    iam.gke.io/gcp-service-account: cv-cloudsql-proxy@PROJECT_ID.iam.gserviceaccount.com
